{
    "title": "Curation Test",
    "viewId": "default",
    "packageType": "dataset",
    "description": "Created by Mike so that he can understand how curation works",
    "redbox:newForm": "false",
    "redbox:formVersion": "1.6.2-SNAPSHOT",
    "dc:title": "Curation Test",
    "dc:type.rdf:PlainLiteral": "dataset",
    "dc:type.skos:prefLabel": "Dataset",
    "dc:created": "2013-10-18",
    "dc:modified": "",
    "dc:language.dc:identifier": "http://id.loc.gov/vocabulary/iso639-2/eng",
    "dc:language.skos:prefLabel": "English",
    "dc:coverage.vivo:DateTimeInterval.vivo:start": "1990",
    "dc:coverage.vivo:DateTimeInterval.vivo:end": "2019",
    "dc:coverage.redbox:timePeriod": "21st Century",
    "dc:coverage.vivo:GeographicLocation.1.dc:type": "",
    "dc:coverage.vivo:GeographicLocation.1.redbox:wktRaw": "",
    "dc:coverage.vivo:GeographicLocation.1.rdf:PlainLiteral": "",
    "dc:coverage.vivo:GeographicLocation.1.geo:long": "",
    "dc:coverage.vivo:GeographicLocation.1.geo:lat": "",
    "dc:coverage.vivo:GeographicLocation.1.dc:identifier": "",
    "dc:description": "Created by Mike so that he can understand how curation works",
    "dc:relation.swrc:Publication.1.dc:identifier": "",
    "dc:relation.swrc:Publication.1.dc:title": "",
    "dc:relation.swrc:Publication.1.skos:note": "",
    "dc:relation.bibo:Website.1.dc:identifier": "",
    "dc:relation.bibo:Website.1.dc:title": "",
    "dc:relation.bibo:Website.1.skos:note": "",
    "dc:relation.vivo:Dataset.1.dc:identifier": "",
    "dc:relation.vivo:Dataset.1.vivo:Relationship.rdf:PlainLiteral": "hasAssociationWith",
    "dc:relation.vivo:Dataset.1.vivo:Relationship.skos:prefLabel": "Has association with:",
    "dc:relation.vivo:Dataset.1.dc:title": "",
    "dc:relation.vivo:Dataset.1.skos:note": "",
    "dc:relation.vivo:Dataset.1.redbox:origin": "on",
    "dc:relation.vivo:Dataset.1.redbox:publish": "",
    "dc:relation.vivo:Service.1.dc:identifier": "au.edu.uts/services/RLABSERVICE00001",
    "dc:relation.vivo:Service.1.vivo:Relationship.rdf:PlainLiteral": "isProducedBy",
    "dc:relation.vivo:Service.1.vivo:Relationship.skos:prefLabel": "Is produced by:",
    "dc:relation.vivo:Service.1.dc:title": "University of Technology Sydney - UTS Labshare iRobot Rig",
    "dc:relation.vivo:Service.1.skos:note": "",
    "dc:creator.foaf:Person.1.dc:identifier": "http://hdl.handle.net/11057/id59416f87",
    "dc:creator.foaf:Person.1.foaf:name": "De La Villefromoy, Michel",
    "dc:creator.foaf:Person.1.foaf:title": "Mr.",
    "dc:creator.foaf:Person.1.redbox:isCoPrimaryInvestigator": "on",
    "dc:creator.foaf:Person.1.redbox:isPrimaryInvestigator": "on",
    "dc:creator.foaf:Person.1.foaf:givenName": "Michel",
    "dc:creator.foaf:Person.1.foaf:familyName": "De La Villefromoy",
    "dc:creator.foaf:Person.1.foaf:Organization.dc:identifier": "au.edu.uts/parties/group/927",
    "dc:creator.foaf:Person.1.foaf:Organization.skos:prefLabel": "FEIT.School of Computing and Communications",
    "locrel:prc.foaf:Person.dc:identifier": "",
    "locrel:prc.foaf:Person.foaf:name": "",
    "locrel:prc.foaf:Person.foaf:title": "",
    "locrel:prc.foaf:Person.foaf:givenName": "",
    "locrel:prc.foaf:Person.foaf:familyName": "",
    "locrel:prc.foaf:Person.foaf:email": "",
    "swrc:supervisor.foaf:Person.1.dc:identifier": "",
    "swrc:supervisor.foaf:Person.1.foaf:name": "",
    "swrc:supervisor.foaf:Person.1.foaf:title": "",
    "swrc:supervisor.foaf:Person.1.foaf:givenName": "",
    "swrc:supervisor.foaf:Person.1.foaf:familyName": "",
    "dc:contributor.locrel:clb.1.foaf:Agent": "",
    "dc:subject.vivo:keyword.1.rdf:PlainLiteral": "curation",
    "dc:subject.anzsrc:toa.rdf:resource": "",
    "dc:subject.anzsrc:toa.skos:prefLabel": "",
    "dc:accessRights.skos:prefLabel": "public",
    "dc:accessRights.dc:identifier": "",
    "dc:accessRights.dc:RightsStatement.skos:prefLabel": "",
    "dc:accessRights.dc:RightsStatement.dc:identifier": "",
    "dc:license.skos:prefLabel": "",
    "dc:license.dc:identifier": "",
    "dc:license.rdf:Alt.skos:prefLabel": "",
    "dc:license.rdf:Alt.dc:identifier": "",
    "dc:identifier.rdf:PlainLiteral": "",
    "dc:identifier.dc:type.rdf:PlainLiteral": "handle",
    "dc:identifier.dc:type.skos:prefLabel": "HANDLE System Identifier",
    "dc:identifier.redbox:origin": "internal",
    "vivo:Location.vivo:GeographicLocation.gn:name": "null",
    "vivo:Location.vivo:GeographicLocation.skos:note": "null",
    "redbox:retentionPeriod": "Forever",
    "vivo:Location.vivo:webaddress:private": "",
    "vivo:Location.vivo:files:private": "",
    "vivo:Location.vivo:physcials:private": "",
    "vivo:Location.vivo:webaddress": "",
    "vivo:Location.vivo:files": "",
    "vivo:Location.vivo:physcials": "University of Cloud-Cuckoo-Land",
    "dc:extent": "Everywhere",
    "redbox:disposalDate": "",
    "locrel:own.foaf:Agent.1.foaf:name": "",
    "locrel:dtm.foaf:Agent.foaf:name": "",
    "foaf:Organization.dc:identifier": "",
    "foaf:Organization.skos:prefLabel": "",
    "foaf:fundedBy.foaf:Agent.1.skos:prefLabel": "",
    "foaf:fundedBy.foaf:Agent.1.dc:identifier": "",
    "foaf:fundedBy.vivo:Grant.1.redbox:internalGrant": "",
    "foaf:fundedBy.vivo:Grant.1.redbox:grantNumber": "",
    "foaf:fundedBy.vivo:Grant.1.dc:identifier": "",
    "foaf:fundedBy.vivo:Grant.1.skos:prefLabel": "",
    "swrc:ResearchProject.dc:title": "",
    "locrel:dpt.foaf:Person.foaf:name": "",
    "dc:SizeOrDuration": "",
    "dc:Policy": "",
    "redbox:ManagementPlan.redbox:hasPlan": null,
    "redbox:ManagementPlan.skos:note": "",
    "skos:note.1.dc:created": "2013-10-18 16:33:42",
    "skos:note.1.foaf:name": "admin",
    "skos:note.1.dc:description": "",
    "dc:biblioGraphicCitation.skos:prefLabel": "",
    "dc:biblioGraphicCitation.redbox:sendCitation": "",
    "dc:biblioGraphicCitation.dc:hasPart.dc:identifier.skos:note": "useCuration",
    "dc:biblioGraphicCitation.dc:hasPart.locrel:ctb.1.foaf:title": "",
    "dc:biblioGraphicCitation.dc:hasPart.locrel:ctb.1.foaf:givenName": "",
    "dc:biblioGraphicCitation.dc:hasPart.locrel:ctb.1.foaf:familyName": "",
    "dc:biblioGraphicCitation.dc:hasPart.dc:title": "",
    "dc:biblioGraphicCitation.dc:hasPart.dc:hasVersion.rdf:PlainLiteral": "",
    "dc:biblioGraphicCitation.dc:hasPart.dc:publisher.rdf:PlainLiteral": "",
    "dc:biblioGraphicCitation.dc:hasPart.vivo:Publisher.vivo:Location": "",
    "dc:biblioGraphicCitation.dc:hasPart.dc:date.1.rdf:PlainLiteral": "",
    "dc:biblioGraphicCitation.dc:hasPart.dc:date.2.rdf:PlainLiteral": "",
    "dc:biblioGraphicCitation.dc:hasPart.dc:date.1.dc:type.rdf:PlainLiteral": "",
    "dc:biblioGraphicCitation.dc:hasPart.dc:date.2.dc:type.rdf:PlainLiteral": "",
    "dc:biblioGraphicCitation.dc:hasPart.dc:date.1.dc:type.skos:prefLabel": "",
    "dc:biblioGraphicCitation.dc:hasPart.dc:date.2.dc:type.skos:prefLabel": "",
    "dc:biblioGraphicCitation.dc:hasPart.bibo:Website.dc:identifier": "",
    "dc:biblioGraphicCitation.dc:hasPart.skos:scopeNote": "",
    "redbox:submissionProcess.redbox:submitted": "null",
    "redbox:submissionProcess.dc:date": "",
    "redbox:submissionProcess.dc:description": "",
    "redbox:submissionProcess.locrel:prc.foaf:Person.foaf:name": "",
    "redbox:submissionProcess.locrel:prc.foaf:Person.foaf:phone": "",
    "redbox:submissionProcess.locrel:prc.foaf:Person.foaf:mbox": "",
    "redbox:submissionProcess.dc:title": "",
    "redbox:submissionProcess.skos:note": "",
    "redbox:embargo.redbox:isEmbargoed": "",
    "redbox:embargo.dc:date": "",
    "redbox:embargo.skos:note": "",
    "dc:relation.redbox:TechnicalMetadata.1.dc:identifier": "",
    "dc:relation.redbox:TechnicalMetadata.1.dc:title": "",
    "dc:relation.redbox:TechnicalMetadata.1.dc:type": "",
    "dc:relation.redbox:TechnicalMetadata.1.dc:conformsTo": "",
    "xmlns:dc": "http://dublincore.org/documents/2008/01/14/dcmi-terms/",
    "xmlns:foaf": "http://xmlns.com/foaf/spec/",
    "xmlns:anzsrc": "http://purl.org/anzsrc/",
    "metaList": [
        "dc:title",
        "dc:type.rdf:PlainLiteral",
        "dc:type.skos:prefLabel",
        "dc:created",
        "dc:modified",
        "dc:language.dc:identifier",
        "dc:language.skos:prefLabel",
        "redbox:formVersion",
        "redbox:newForm",
        "dc:coverage.vivo:DateTimeInterval.vivo:start",
        "dc:coverage.vivo:DateTimeInterval.vivo:end",
        "dc:coverage.redbox:timePeriod",
        "dc:coverage.vivo:GeographicLocation.1.dc:type",
        "dc:coverage.vivo:GeographicLocation.2.dc:type",
        "dc:coverage.vivo:GeographicLocation.3.dc:type",
        "dc:coverage.vivo:GeographicLocation.4.dc:type",
        "dc:coverage.vivo:GeographicLocation.1.redbox:wktRaw",
        "dc:coverage.vivo:GeographicLocation.2.redbox:wktRaw",
        "dc:coverage.vivo:GeographicLocation.3.redbox:wktRaw",
        "dc:coverage.vivo:GeographicLocation.4.redbox:wktRaw",
        "dc:coverage.vivo:GeographicLocation.1.rdf:PlainLiteral",
        "dc:coverage.vivo:GeographicLocation.2.rdf:PlainLiteral",
        "dc:coverage.vivo:GeographicLocation.3.rdf:PlainLiteral",
        "dc:coverage.vivo:GeographicLocation.4.rdf:PlainLiteral",
        "dc:coverage.vivo:GeographicLocation.1.geo:long",
        "dc:coverage.vivo:GeographicLocation.2.geo:long",
        "dc:coverage.vivo:GeographicLocation.3.geo:long",
        "dc:coverage.vivo:GeographicLocation.4.geo:long",
        "dc:coverage.vivo:GeographicLocation.1.geo:lat",
        "dc:coverage.vivo:GeographicLocation.2.geo:lat",
        "dc:coverage.vivo:GeographicLocation.3.geo:lat",
        "dc:coverage.vivo:GeographicLocation.4.geo:lat",
        "dc:coverage.vivo:GeographicLocation.1.dc:identifier",
        "dc:coverage.vivo:GeographicLocation.2.dc:identifier",
        "dc:coverage.vivo:GeographicLocation.3.dc:identifier",
        "dc:coverage.vivo:GeographicLocation.4.dc:identifier",
        "dc:description",
        "dc:relation.swrc:Publication.1.dc:identifier",
        "dc:relation.swrc:Publication.1.dc:title",
        "dc:relation.swrc:Publication.1.skos:note",
        "dc:relation.bibo:Website.1.dc:identifier",
        "dc:relation.bibo:Website.1.dc:title",
        "dc:relation.bibo:Website.1.skos:note",
        "dc:relation.vivo:Dataset.1.dc:identifier",
        "dc:relation.vivo:Dataset.1.vivo:Relationship.rdf:PlainLiteral",
        "dc:relation.vivo:Dataset.1.vivo:Relationship.skos:prefLabel",
        "dc:relation.vivo:Dataset.1.dc:title",
        "dc:relation.vivo:Dataset.1.skos:note",
        "dc:relation.vivo:Dataset.1.redbox:origin",
        "dc:relation.vivo:Dataset.1.redbox:publish",
        "dc:relation.vivo:Service.1.dc:identifier",
        "dc:relation.vivo:Service.1.vivo:Relationship.rdf:PlainLiteral",
        "dc:relation.vivo:Service.1.vivo:Relationship.skos:prefLabel",
        "dc:relation.vivo:Service.1.dc:title",
        "dc:relation.vivo:Service.1.skos:note",
        "dc:creator.foaf:Person.1.dc:identifier",
        "dc:creator.foaf:Person.1.foaf:name",
        "dc:creator.foaf:Person.1.foaf:title",
        "dc:creator.foaf:Person.1.redbox:isCoPrimaryInvestigator",
        "dc:creator.foaf:Person.1.redbox:isPrimaryInvestigator",
        "dc:creator.foaf:Person.1.foaf:givenName",
        "dc:creator.foaf:Person.1.foaf:familyName",
        "dc:creator.foaf:Person.1.foaf:Organization.dc:identifier",
        "dc:creator.foaf:Person.1.foaf:Organization.skos:prefLabel",
        "locrel:prc.foaf:Person.dc:identifier",
        "locrel:prc.foaf:Person.foaf:name",
        "locrel:prc.foaf:Person.foaf:title",
        "locrel:prc.foaf:Person.foaf:givenName",
        "locrel:prc.foaf:Person.foaf:familyName",
        "locrel:prc.foaf:Person.foaf:email",
        "swrc:supervisor.foaf:Person.1.dc:identifier",
        "swrc:supervisor.foaf:Person.1.foaf:name",
        "swrc:supervisor.foaf:Person.1.foaf:title",
        "swrc:supervisor.foaf:Person.1.foaf:givenName",
        "swrc:supervisor.foaf:Person.1.foaf:familyName",
        "dc:contributor.locrel:clb.1.foaf:Agent",
        "dc:subject.vivo:keyword.1.rdf:PlainLiteral",
        "dc:subject.anzsrc:toa.rdf:resource",
        "dc:subject.anzsrc:toa.skos:prefLabel",
        "dc:accessRights.skos:prefLabel",
        "dc:accessRights.dc:identifier",
        "dc:accessRights.dc:RightsStatement.skos:prefLabel",
        "dc:accessRights.dc:RightsStatement.dc:identifier",
        "dc:license.skos:prefLabel",
        "dc:license.dc:identifier",
        "dc:license.rdf:Alt.skos:prefLabel",
        "dc:license.rdf:Alt.dc:identifier",
        "dc:identifier.rdf:PlainLiteral",
        "dc:identifier.dc:type.rdf:PlainLiteral",
        "dc:identifier.dc:type.skos:prefLabel",
        "dc:identifier.redbox:origin",
        "vivo:Location.vivo:GeographicLocation.gn:name",
        "vivo:Location.vivo:GeographicLocation.skos:note",
        "redbox:retentionPeriod",
        "vivo:Location.vivo:webaddress:private",
        "vivo:Location.vivo:files:private",
        "vivo:Location.vivo:physcials:private",
        "vivo:Location.vivo:webaddress",
        "vivo:Location.vivo:files",
        "vivo:Location.vivo:physcials",
        "dc:extent",
        "redbox:disposalDate",
        "locrel:own.foaf:Agent.1.foaf:name",
        "locrel:dtm.foaf:Agent.foaf:name",
        "foaf:Organization.dc:identifier",
        "foaf:Organization.skos:prefLabel",
        "foaf:fundedBy.foaf:Agent.1.skos:prefLabel",
        "foaf:fundedBy.foaf:Agent.1.dc:identifier",
        "foaf:fundedBy.vivo:Grant.1.redbox:internalGrant",
        "foaf:fundedBy.vivo:Grant.1.redbox:grantNumber",
        "foaf:fundedBy.vivo:Grant.1.dc:identifier",
        "foaf:fundedBy.vivo:Grant.1.skos:prefLabel",
        "swrc:ResearchProject.dc:title",
        "locrel:dpt.foaf:Person.foaf:name",
        "dc:SizeOrDuration",
        "dc:Policy",
        "redbox:ManagementPlan.redbox:hasPlan",
        "redbox:ManagementPlan.skos:note",
        "skos:note.1.dc:created",
        "skos:note.1.foaf:name",
        "skos:note.1.dc:description",
        "dc:biblioGraphicCitation.skos:prefLabel",
        "dc:biblioGraphicCitation.redbox:sendCitation",
        "dc:biblioGraphicCitation.dc:hasPart.dc:identifier.skos:note",
        "dc:biblioGraphicCitation.dc:hasPart.locrel:ctb.1.foaf:title",
        "dc:biblioGraphicCitation.dc:hasPart.locrel:ctb.1.foaf:givenName",
        "dc:biblioGraphicCitation.dc:hasPart.locrel:ctb.1.foaf:familyName",
        "dc:biblioGraphicCitation.dc:hasPart.dc:title",
        "dc:biblioGraphicCitation.dc:hasPart.dc:hasVersion.rdf:PlainLiteral",
        "dc:biblioGraphicCitation.dc:hasPart.dc:publisher.rdf:PlainLiteral",
        "dc:biblioGraphicCitation.dc:hasPart.vivo:Publisher.vivo:Location",
        "dc:biblioGraphicCitation.dc:hasPart.dc:date.1.rdf:PlainLiteral",
        "dc:biblioGraphicCitation.dc:hasPart.dc:date.2.rdf:PlainLiteral",
        "dc:biblioGraphicCitation.dc:hasPart.dc:date.1.dc:type.rdf:PlainLiteral",
        "dc:biblioGraphicCitation.dc:hasPart.dc:date.2.dc:type.rdf:PlainLiteral",
        "dc:biblioGraphicCitation.dc:hasPart.dc:date.1.dc:type.skos:prefLabel",
        "dc:biblioGraphicCitation.dc:hasPart.dc:date.2.dc:type.skos:prefLabel",
        "dc:biblioGraphicCitation.dc:hasPart.bibo:Website.dc:identifier",
        "dc:biblioGraphicCitation.dc:hasPart.skos:scopeNote",
        "redbox:submissionProcess.redbox:submitted",
        "redbox:submissionProcess.dc:date",
        "redbox:submissionProcess.dc:description",
        "redbox:submissionProcess.locrel:prc.foaf:Person.foaf:name",
        "redbox:submissionProcess.locrel:prc.foaf:Person.foaf:phone",
        "redbox:submissionProcess.locrel:prc.foaf:Person.foaf:mbox",
        "redbox:submissionProcess.dc:title",
        "redbox:submissionProcess.skos:note",
        "redbox:embargo.redbox:isEmbargoed",
        "redbox:embargo.dc:date",
        "redbox:embargo.skos:note",
        "dc:relation.redbox:TechnicalMetadata.1.dc:identifier",
        "dc:relation.redbox:TechnicalMetadata.1.dc:title",
        "dc:relation.redbox:TechnicalMetadata.1.dc:type",
        "dc:relation.redbox:TechnicalMetadata.1.dc:conformsTo",
        "xmlns:dc",
        "xmlns:foaf",
        "xmlns:anzsrc"
    ],
    "dc:coverage.vivo:GeographicLocation.2.dc:type": "text",
    "dc:coverage.vivo:GeographicLocation.3.dc:type": "",
    "dc:coverage.vivo:GeographicLocation.4.dc:type": "text",
    "dc:coverage.vivo:GeographicLocation.2.redbox:wktRaw": "POINT(150.81207275391 -34.499388907898)",
    "dc:coverage.vivo:GeographicLocation.3.redbox:wktRaw": "",
    "dc:coverage.vivo:GeographicLocation.4.redbox:wktRaw": "POINT(149.2300415039 -24.579181047342)",
    "dc:coverage.vivo:GeographicLocation.2.rdf:PlainLiteral": "POINT(150.81207275391 -34.499388907898)",
    "dc:coverage.vivo:GeographicLocation.3.rdf:PlainLiteral": "",
    "dc:coverage.vivo:GeographicLocation.4.rdf:PlainLiteral": "POINT(149.2300415039 -24.579181047342)",
    "dc:coverage.vivo:GeographicLocation.2.geo:long": "",
    "dc:coverage.vivo:GeographicLocation.3.geo:long": "",
    "dc:coverage.vivo:GeographicLocation.4.geo:long": "",
    "dc:coverage.vivo:GeographicLocation.2.geo:lat": "",
    "dc:coverage.vivo:GeographicLocation.3.geo:lat": "",
    "dc:coverage.vivo:GeographicLocation.4.geo:lat": "",
    "dc:coverage.vivo:GeographicLocation.2.dc:identifier": "",
    "dc:coverage.vivo:GeographicLocation.3.dc:identifier": "",
    "dc:coverage.vivo:GeographicLocation.4.dc:identifier": ""
}
